webtalk_init -webtalk_dir Y:/TEMP/labo2_ta3_zebi/labo2_ta3_zebi.sim/sim_1/behav/xsim/xsim.dir/multiplexeur_labo2_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 22 08:24:45 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174126023_174126024_207295007_909" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "70db9b08-01ee-46d5-b5b0-abe940e80b4c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0e33bd9f54d34087a4577dd3b956b218" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6408_KB" -context "xsim\\usage"
webtalk_transmit -clientid 181967709 -regid "174126023_174126024_207295007_909" -xml Y:/TEMP/labo2_ta3_zebi/labo2_ta3_zebi.sim/sim_1/behav/xsim/xsim.dir/multiplexeur_labo2_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html Y:/TEMP/labo2_ta3_zebi/labo2_ta3_zebi.sim/sim_1/behav/xsim/xsim.dir/multiplexeur_labo2_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm Y:/TEMP/labo2_ta3_zebi/labo2_ta3_zebi.sim/sim_1/behav/xsim/xsim.dir/multiplexeur_labo2_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
